export const basePath: string = "/request-a-military-service-record";

export const Paths = {
  DO_YOU_HAVE_A_PROOF_OF_DEATH: `${basePath}/do-you-have-a-proof-of-death/`,
  HOW_WE_PROCESS_REQUESTS: `${basePath}/how-we-process-requests/`,
  BEFORE_YOU_START: `${basePath}/before-you-start/`,
  YOU_HAVE_CANCELLED_YOUR_REQUEST: `${basePath}/request-cancelled/`,
  ARE_YOU_SURE_YOU_WANT_TO_CANCEL: `${basePath}/are-you-sure-you-want-to-cancel/`,
  YOU_MAY_WANT_TO_CHECK_ANCESTRY: `${basePath}/check-ancestry/`,
  HAVE_YOU_PREVIOUSLY_MADE_A_REQUEST: `${basePath}/have-you-previously-made-a-request/`,
  HOW_DO_YOU_WANT_YOUR_ORDER_PROCESSED: `${basePath}/how-do-you-want-your-order-processed/`,
  IS_SERVICE_PERSON_ALIVE: `${basePath}/is-service-person-alive/`,
  JOURNEY_START: `${basePath}/`,
  MUST_SUBMIT_SUBJECT_ACCESS: `${basePath}/must-submit-subject-access/`,
  REQUEST_SUBMITTED: `${basePath}/request-submitted/`,
  SELECT_SERVICE_BRANCH: `${basePath}/service-branch/`,
  SERVICE_BRANCH: `${basePath}/service-branch/`,
  SERVICE_PERSON_DETAILS: `${basePath}/service-person-details/`,
  UPLOAD_A_PROOF_OF_DEATH: `${basePath}/upload-a-proof-of-death/`,
  ARE_YOU_SURE_YOU_WANT_TO_PROCEED_WITHOUT_A_PROOF_OF_DEATH: `${basePath}/are-you-sure-you-want-to-proceed-without-proof-of-death/`,
  WERE_THEY_A_COMMISSIONED_OFFICER: `${basePath}/were-they-a-commissioned-officer/`,
  WE_DO_NOT_HAVE_RECORDS_FOR_PEOPLE_BORN_AFTER: `${basePath}/we-do-not-have-records-for-people-born-after/`,
  WE_DO_NOT_HAVE_RECORDS_FOR_PEOPLE_BORN_BEFORE: `${basePath}/we-do-not-have-records-for-people-born-before/`,
  WE_ARE_UNLIKELY_TO_HOLD_OFFICER_RECORDS__RAF: `${basePath}/we-are-unlikely-to-hold-royal-air-force-officer-records/`,
  WE_ARE_UNLIKELY_TO_HOLD_OFFICER_RECORDS__GENERIC: `${basePath}/we-are-unlikely-to-hold-officer-records-for-this-branch/`,
  WE_ARE_UNLIKELY_TO_HOLD_OFFICER_RECORDS__ARMY: `${basePath}/we-are-unlikely-to-hold-army-officer-records/`,
  WE_DO_NOT_HAVE_ROYAL_NAVY_SERVICE_RECORDS: `${basePath}/we-do-not-have-royal-navy-service-branch-records/`,
  WE_ARE_UNLIKELY_TO_LOCATE_THIS_RECORD: `${basePath}/we-are-unlikely-to-locate-this-record/`,
  WE_MAY_HOLD_THIS_RECORD: `${basePath}/we-may-hold-this-record/`,
  WHAT_WAS_THEIR_DATE_OF_BIRTH: `${basePath}/what-was-their-date-of-birth/`,
  YOUR_DETAILS: `${basePath}/your-details/`,
  YOUR_POSTAL_ADDRESS: `${basePath}/your-postal-address/`,
};
