name: Run Playwright tests

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: lts/jod
    - name: Get installed Playwright version
      id: playwright-version
      run: echo "PLAYWRIGHT_VERSION=$(jq -r '(.packages."node_modules/@playwright/test".version)' package-lock.json)" >> $GITHUB_OUTPUT
      shell: bash
    - name: Cache playwright binaries
      uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3.5.0
      id: playwright-cache
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.PLAYWRIGHT_VERSION }}
    - name: Install test dependencies
      run: npm ci
      shell: bash
    - run: npx playwright install --with-deps
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      shell: bash
    - run: npx playwright install-deps
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      shell: bash
    - name: Install system dependencies for WebKit
      # Some WebKit dependencies seem to lay outside the cache and will need to be installed separately
      if: steps.playwright-cache.outputs.cache-hit == 'true'
      run: npx playwright install-deps webkit
      shell: bash
    - name: Write .env for compose (explicit)
      run: |
        echo "CONFIG=config.Test" > .env
        echo "ENVIRONMENT_NAME=test" >> .env
        cat .env
      shell: bash
    - name: Start service
      env:
        ENVIRONMENT_NAME: test
        CONFIG: config.Test
      run: docker compose up --detach --wait --wait-timeout 300 app || docker compose logs app
      shell: bash
    - name: Run tests
      run: CI=true npx playwright test --project=chromium --grep-invert "@wip"
      shell: bash
