name: Run Python tests

runs:
  using: "composite"
  steps:
    - name: Start app container
      run: docker compose up --detach --wait --wait-timeout 300 app || docker compose logs app
      shell: bash
    - name: Create database
      run: docker compose exec dev poetry run python create_database.py
      shell: bash
    - name: Run tests
      run: docker compose exec app poetry run python -m pytest
      shell: bash
